############# get all products ##########
GET http://localhost:3000/api/products/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY1YjllYzFkMWMwYjBhMjA1YTk3NjkiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYxNzI4MDI3NywiZXhwIjoxNjE3NTM5NDc3fQ.Z0Tbc7R8tzAl6_I-_3An19rzoRCZwp0-eZVqeFOmfXs
######## get product #########
GET http://localhost:3000/api/products/product/6065be252cc9b504a4df88ab

######## update product ########

PUT http://localhost:3000/api/products/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY1YjllYzFkMWMwYjBhMjA1YTk3NjkiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYxNzI4MDI3NywiZXhwIjoxNjE3NTM5NDc3fQ.Z0Tbc7R8tzAl6_I-_3An19rzoRCZwp0-eZVqeFOmfXs

{
    "id": "6065be252cc9b504a4df88ab",
    "newData": {
        "price": 400
    }
}

######## delete product ######60664df75aed0107fc13d354
DELETE  http://localhost:3000/api/products/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY1YjllYzFkMWMwYjBhMjA1YTk3NjkiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYxNzI4MDI3NywiZXhwIjoxNjE3NTM5NDc3fQ.Z0Tbc7R8tzAl6_I-_3An19rzoRCZwp0-eZVqeFOmfXs

{
    "id": "60684e23a2f6ce13e0e7f19e"
}

################ get all categories categories
GET http://localhost:3000/api/categories/

######### get names of categories
GET http://localhost:3000/api/categories/names

######### get category by id
GET http://localhost:3000/api/categories/get/60684953697ea511ecb982db


######## update Category
PUT http://localhost:3000/api/categories/update/606656b26486d31554057bf1
Content-Type: application/json

{
    "name": "new product"
}

##### delete category and all products in this category
DELETE  http://localhost:3000/api/categories/delete/60684e97a2f6ce13e0e7f1a0
